<?php
function eventissimo_eventsConnectFacebook($title, $link, $description,$start_time, $end_time,$city,$address,$idPost,$token,$iduser,$privacy_type,$idevents=0){
	
	$upload_dir = wp_upload_dir(); 

	$facebook = accessFacebook();
	//$posthumbnail = wp_get_attachment_image_src( get_the_post_thumbnail($idPost, 'large'));
	$post_thumbnail_id = get_post_thumbnail_id($idPost);
	
	
	if ((isset($post_thumbnail_id)) && ($post_thumbnail_id!="")){
		$cover_image_url = wp_get_attachment_metadata($post_thumbnail_id);
		$dirname = dirname($cover_image_url["file"]);
		$post_thumbnail_url = isset($cover_image_url["sizes"]["fb_cover_image"]) ? $cover_image_url["sizes"]["fb_cover_image"]["file"] : $cover_image_url["sizes"]["large"]["file"];
		$post_thumbnail_url = $upload_dir["basedir"] . "/" . $dirname . "/"  . $post_thumbnail_url;
	} else {
		$post_thumbnail_url ="";
	}


	if ($title=="") $title= __("No title","eventissimo");
	
	$eventInfo = array(
		"name"=> $title,
		"start_time"=>$start_time,
		"description"=> $description,
		"location"=>$city . " " . $address ,
		"venue" =>  $city . " " . $address, 
		"privacy_type" => $privacy_type,
		"privacy" => $privacy_type,
	);
	
	if ($end_time!="")
		$eventInfo["end_time"] = $end_time;
		
	if ($idevents==0){
		try{
			$result = $facebook->api('/' . $iduser . '/events?access_token=' . $token,'post',$eventInfo);
			//Post Link Site
			$post_url = get_permalink($idPost);
			$description = $description;
			$message = __("This event was generated by","eventissimo") . " " . get_bloginfo('name');
			eventissimo_postEventFacebook($token,$post_url,$description,$title,$result['id'],$message);
			
			//Post Cover
			eventissimo_postCoverImage($post_thumbnail_url,$result['id']);
			
			return $result['id'];
	
		}catch( Exception $e){
			
			echo $e;

		}
		
		
		
	} else {
		
		try{
			//Check title, adress change
			
			$apiCheck = "/" . $idevents . "/event?fields=name,location,description";
			$result = $facebook->api($apiCheck);
			if ($result["name"]==$eventInfo["name"]) unset ($eventInfo["name"]);
			if ($result["description"]==$eventInfo["description"]) unset ($eventInfo["description"]);
			if ($result["location"]==$eventInfo["location"]) {
				unset ($eventInfo["location"]);
				unset ($eventInfo["venue"]);
			}
		
			$result = $facebook->api('/' . $idevents,'post',$eventInfo);
			//Post Cover
			eventissimo_postCoverImage($post_thumbnail_url,$idevents);
			return $result;
		}catch( Exception $e){
			echo $e;
		}
	}
}
?>